version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  
  exclusions:
    rules:
      # Exclude all linters from test files
      - path: '(.+)_test\.go'
        linters:
          - dupl
          - errcheck
          - copyloopvar
          - ginkgolinter
          - goconst
          - gocyclo
          - govet
          - ineffassign
          - misspell
          - nakedret
          - prealloc
          - revive
          - staticcheck
          - unconvert
          - unparam
          - unused
      
      # Exclude all linters from test directory
      - path: 'test/'
        linters:
          - dupl
          - errcheck
          - copyloopvar
          - ginkgolinter
          - goconst
          - gocyclo
          - govet
          - ineffassign
          - misspell
          - nakedret
          - prealloc
          - revive
          - staticcheck
          - unconvert
          - unparam
          - unused