apiVersion: openawareness.syndlex/v1beta1
kind: MimirAlertTenant
metadata:
  name: devops-alerts
  labels:
    app.kubernetes.io/name: openawareness-controller
    app.kubernetes.io/component: alert-config
    app.kubernetes.io/instance: e2e-mimir
    environment: e2e-test
    team: devops
  annotations:
    # Reference to the ClientConfig that provides Mimir connection details
    openawareness.io/client-name: "e2e-mimir-client"
    # Mimir namespace/tenant for this alertmanager configuration
    # This enables multi-tenant isolation in Mimir
    openawareness.io/mimir-namespace: "devops-team"
spec:
  # Template files for notification templates
  # These templates define how alert notifications are formatted
  templateFiles:
    default_template: |
      {{ define "__alertmanager" }}AlertManager{{ end }}
      {{ define "__alertmanagerURL" }}{{ .ExternalURL }}/#/alerts?receiver={{ .Receiver | urlquery }}{{ end }}
      
      {{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}
      
      {{ define "__description" }}{{ end }}
      
      {{ define "__text_alert_list" }}{{ range . }}
      *Alert:* {{ .Labels.alertname }}
      *Severity:* {{ .Labels.severity }}
      *Summary:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      
      *Labels:*
      {{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
      {{ end }}
      *Source:* {{ .GeneratorURL }}
      {{ end }}{{ end }}

  # Alertmanager configuration in YAML format
  # This configuration is specific to the devops-team tenant
  alertmanagerConfig: |
    global:
      # SMTP configuration for email notifications
      # In e2e tests, these are example values
      smtp_smarthost: 'mailhog.default.svc.cluster.local:1025'
      smtp_from: 'alertmanager@devops-team.local'
      smtp_require_tls: false
    
    # Reference to template files defined above
    templates:
      - 'default_template'
    
    # Routing tree for notifications
    route:
      # Default receiver for all alerts
      receiver: 'devops-default'
      
      # Group alerts by these labels to reduce notification spam
      group_by: ['alertname', 'severity', 'service']
      
      # Wait 30s before sending initial notification
      # This allows grouping of alerts that fire simultaneously
      group_wait: 30s
      
      # Wait 5m before sending notification about new alerts in existing group
      group_interval: 5m
      
      # Wait 4h before re-sending a notification for ongoing alert
      repeat_interval: 4h
      
      # Child routes for specific alert routing
      routes:
        # Route critical alerts to dedicated receiver
        - match:
            severity: critical
          receiver: 'devops-critical'
          # Continue to also send to default receiver
          continue: false
          # Send critical alerts immediately
          group_wait: 10s
          
        # Route warning alerts
        - match:
            severity: warning
          receiver: 'devops-warning'
          
        # Route pipeline-specific alerts
        - match:
            component: pipeline
          receiver: 'devops-pipeline'
          group_by: ['alertname', 'pipeline', 'stage']
    
    # Alert receivers configuration
    receivers:
      # Default receiver for all alerts
      - name: 'devops-default'
        email_configs:
          - to: 'devops-team@example.org'
            headers:
              Subject: '{{ template "__subject" . }}'
            html: |
              <h2>DevOps Alert</h2>
              <p>{{ template "__text_alert_list" .Alerts }}</p>
            send_resolved: true
      
      # Critical alerts receiver
      - name: 'devops-critical'
        email_configs:
          - to: 'devops-oncall@example.org'
            headers:
              Subject: '[CRITICAL] {{ template "__subject" . }}'
              Priority: 'urgent'
            html: |
              <h1 style="color: red;">CRITICAL ALERT</h1>
              <p>{{ template "__text_alert_list" .Alerts }}</p>
            send_resolved: true
      
      # Warning alerts receiver
      - name: 'devops-warning'
        email_configs:
          - to: 'devops-team@example.org'
            headers:
              Subject: '[WARNING] {{ template "__subject" . }}'
            html: |
              <h2 style="color: orange;">Warning Alert</h2>
              <p>{{ template "__text_alert_list" .Alerts }}</p>
            send_resolved: true
      
      # Pipeline-specific alerts receiver
      - name: 'devops-pipeline'
        email_configs:
          - to: 'devops-pipeline@example.org'
            headers:
              Subject: '[Pipeline] {{ template "__subject" . }}'
            html: |
              <h2>Pipeline Alert</h2>
              <p>{{ template "__text_alert_list" .Alerts }}</p>
            send_resolved: true
    
    # Inhibition rules to suppress notifications
    # These prevent alert spam by suppressing lower-severity alerts
    # when higher-severity alerts are already firing
    inhibit_rules:
      # Inhibit warning alerts if critical alert is firing for same alertname
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'service']
      
      # Inhibit info alerts if warning or critical is firing
      - source_match:
          severity: 'warning'
        target_match:
          severity: 'info'
        equal: ['alertname', 'service']
